Vagrant.configure("2") do |config|
  config.vm.box_check_update = false

  #App server
  config.vm.define "app" do |app| 
    app.vm.box = "hashicorp/bionic64"
    app.vm.network "private_network", ip: "192.168.56.222"
    app.vm.network "forwarded_port", host: 2223, guest: 22
  end
  
  #DB server
  config.vm.define "db" do |db|
    db.vm.box = "hashicorp/bionic64"
    db.vm.network "private_network", ip: "192.168.56.111"
    db.vm.network "forwarded_port", host: 2225, guest: 22
  end

end
