Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.network "private_network", ip: "192.168.56.2"
  config.vm.network "forwarded_port", id: "ssh", host: 2222, guest: 22
end
