Vagrant.configure("2") do |config|
  config.vm.box_check_update = false

  #App server
  config.vm.define "app" do |app| 
    config.vm.box = "hashicorp/bionic64"
    config.vm.network "private_network", ip: "192.168.56.2"
    config.vm.network "forwarded_port", host: 2223, guest: 22
    # auto_correct: true
  end
  
  #DB server
  config.vm.define "db" do |db|
    config.vm.box = "hashicorp/bionic64"
    config.vm.network "private_network", ip: "192.168.56.13"
    config.vm.network "forwarded_port", host: 2225, guest: 22
      # auto_correct: true
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  end
end
