- name: app
  hosts: application
  tasks:
    - name: update apt
      become: true
      apt:
        update_cache: yes
        
    - name: clone repo
      git:
        repo: 'https://github.com/sorynturda/unnamed-app.git'
        dest: /home/vagrant/unnamed-app

    - name: install jdk
      become: true
      apt: 
        deb: https://builds.openlogic.com/downloadJDK/openlogic-openjdk/21.0.4+7/openlogic-openjdk-21.0.4+7-linux-x64-deb.deb
        
    - name: create jar file
      ansible.builtin.shell: bash -c "cd /home/vagrant/unnamed-app/backend && ./gradlew clean build -x test"

    - name: run jar file
      ansible.builtin.shell: 
        APP=$(ls | tail -n 1) &&
        java -jar $APP
      args:
        chdir: /home/vagrant/unnamed-app/backend/build/libs
        