- name: app
  hosts: application
  tasks:
    - name: update apt
      become: true
      apt:
        update_cache: yes
    - name: clone repo
      git:
        repo: 'https://github.com/sorynturda/unnamed-app.git'
        dest: /home/vagrant/unnamed-app
    - name: install jdk
      become: true
      apt: 
        deb: https://builds.openlogic.com/downloadJDK/openlogic-openjdk/21.0.4+7/openlogic-openjdk-21.0.4+7-linux-x64-deb.deb
    - name: install gradle
      become: true
      apt:
        name: gradle
        state: latest
    - name: Change perm of gradlew
      file: dest=/home/vagrant/unnamed-app/backend/gradlew mode=a+x
    # - name: update gradle
    #   ansible.builtin.shell: /home/vagrant/app/app/backend/gradlew wrapper --gradle-version=8.5
    - name: create jar file
      ansible.builtin.shell: bash -c "cd /home/vagrant/unnamed-app/backend && ./gradlew clean build -x test"
    - name: start the application
      ansible.builtin.shell: 
        cd /home/vagrant/unnamed-app/backend/build/libs && 
        APP=$(ls | tail -n 1) &&
        java -jar $APP