- name: Installing postgres on DB machine
  hosts: database
  tasks:
    - name: Include db task list in play
      become: yes
      import_tasks: db.yml

- name: Cloning the app and configuring the VM
  hosts: application
  tasks:
    - name: Include app task list in play
      become: yes
      import_tasks: app.yml

- name: running the app
  hosts: application
  tasks: 
    - name: Include start task list in play
      become: yes
      import_tasks: start.yml
