- name: Installing postgres on DB machine
  hosts: database
  tasks:
    - name: Include db task list in play
      become: yes
      import_tasks: db.yml

- name: Cloning and starting the app
  hosts: application
  tasks:
    - name: Include app task list in play
      become: yes
      import_tasks: app.yml
